"""Add completed_at to todos for undo functionality

Revision ID: 5217e0e5cb29
Revises: 2bed1c184866
Create Date: 2025-08-10 13:33:51.533851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5217e0e5cb29'
down_revision: Union[str, None] = '2bed1c184866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed_at')
    # ### end Alembic commands ###